Switch to single script, better param handling and checking, stub out template rendering

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -4,13 +4,48 @@ set -e -u -o pipefail
 
 cd "$( dirname "${BASH_SOURCE[0]}" )/.."
 
-pem="$(yq -c -r -M .key_name).pem"
+usage() {
+  [[ "${1:-}" != '' ]] && echo "$@"
+  cat <<EOF
+USAGE: $0 [--profile=PROFILE] [--action=ACTION]
 
-if ! [[ -f "$pem" ]]; then echo "Unable to find pem file $pem"; exit 1; fi
+PROFILE must match a YAML file in values/ - defaults to "demo"
+ACTION is a cloudformation action - default is "deploy"
+EOF
+  exit "{$2:-1}"
+}
+
+# Gets the value of the next option in $@, fails if an additional shift is needed
+# Details at https://github.com/kilna/scratch/blob/master/bash/opt.sh
+opt() {
+  if [[ "${#1}" -gt 2 && "${1:1:1}" != '-' && "${1:2:1}" != '=' ]]; then echo "${1:2}"
+  elif [[ "$1" == *'='* ]]; then echo "${1#*=}"; else echo "$2"; return 1; fi
+}
+
+profile='demo'
+action='deploy'
+while [[ $# -gt 0 ]]; do case "$1" in
+  -p*|--profile*) profile="$(opt "$@")" || shift;;
+  -a*|--action*)  action="$(opt "$@")" || shift;;
+  -h|--help)      usage '' 0;;
+  *)              usage "Unknown option $1" 1;;
+esac; shift; done
+
+values_yaml="$(pwd)/values/$profile.yaml"
+if ! [[ -e "$values_yaml" ]]; then
+  usage "Unable to find values file $values_yaml for profile $profile" 2
+fi
+
+pem_file="$(yq -c -r -M .key_name).pem"
+if ! [[ -e "$pem_file" ]]; then
+  usage "Unable to find pem file $(pwd)/$pem_file" 3
+fi
 
 eval $(ssh-agent)
 ssh-add "$pem"
 
-if [[ "${1:-}" == '' ]]; then echo "USAGE: $0 <deployment profile>"; exit 1; fi
+tmpdir=$(mktmp -d)
+helm template -f "$yalues_yaml" --output-dir "$tmpdir" chart/
 
-helm tempalte -f ""
+
+
